import pizza_diavola from '../Images/pizza-diabola.svg';

export const PizzasData = () => {
	return [
		{
			name: 'Pizza Margarita',
			ingredients: [
				{ ingredient: 'Burrata', basic: false, extra: false, id: 'burrata1' },
				{ ingredient: 'Tomato Sauce', basic: true, id: 'tomato_sauce' },
				{ ingredient: 'Olives', basic: false, extra: false, id: 'olives1' },
			],
			image: pizza_diavola,
			price: 230,
			id: 'margarita',
			vegetarian: false,
			vegan: false,
			spicy: true,
			all_time_favourite: true,
			amount: 1,
		},
		{
			name: 'Pizza Primavera',
			ingredients: [
				{ ingredient: 'Burrata', basic: false, extra: false, id: 'burrata2' },
				{ ingredient: 'Tomato Sauce', basic: true, id: 'tomato_sauce2' },
				{ ingredient: 'Olives', basic: false, extra: false, id: 'olives2' },
			],
			image: pizza_diavola,
			id: 'primavera1',
			price: 200,
			vegetarian: true,
			vegan: false,
			spicy: false,
			all_time_favourite: false,
			amount: 1,
		},
		{
			name: 'Pizza Bufffalina',
			ingredients: [
				{ ingredient: 'Burrata', basic: false, extra: false, id: 'burrata3' },
				{ ingredient: 'Tomato Sauce', basic: true, id: 'tomato_sauce3' },
				{ ingredient: 'Olives', basic: false, extra: false, id: 'olives3' },
			],
			image: pizza_diavola,
			id: 'bufffalina1',
			vegetarian: true,
			vegan: false,
			price: 240,
			spicy: false,
			all_time_favourite: false,
			amount: 1,
		},
		{
			name: 'Pizza Diavola',
			ingredients: [
				{ ingredient: 'Burrata', basic: false, extra: false, id: 'burrata4' },
				{ ingredient: 'Tomato Sauce', basic: true, id: 'tomato_sauce4' },
				{ ingredient: 'Olives', basic: false, extra: false, id: 'olives4' },
			],
			image: pizza_diavola,
			id: 'diavola1',
			vegetarian: false,
			spicy: true,
			price: 240,
			vegan: false,
			all_time_favourite: true,
			amount: 1,
		},
		{
			name: 'Pizza BBQ',
			ingredients: [
				{ ingredient: 'Burrata', basic: false, extra: false, id: 'burrata5' },
				{ ingredient: 'Tomato Sauce', basic: true, id: 'tomato_sauce5' },
				{ ingredient: 'Olives', basic: false, extra: false, id: 'olives5' },
			],
			image: pizza_diavola,
			id: 'bbq4',
			vegetarian: false,
			price: 210,
			spicy: false,
			vegan: false,
			all_time_favourite: true,
			amount: 1,
		},
	];
};
